from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class TuitionTopic(BaseModel):
    topic_id: str
    chapter: Optional[str] = None
    title: str
    description: str
    estimated_duration_mins: int = 45
    order_index: int

class TuitionSyllabus(BaseModel):
    """
    The master template for a class and subject, usually generated by admin.
    """
    student_class: str
    subject: str
    topics: List[TuitionTopic]
    created_at: datetime = Field(default_factory=datetime.utcnow)

class TimetableSlot(BaseModel):
    day_of_week: str  # e.g., "Monday"
    start_time: str   # e.g., "17:00"
    subject: str      # e.g., "Science"

class StudentTimetableConfig(BaseModel):
    """
    The user's preferred weekly routine for tuition.
    """
    student_id: str
    slots: List[TimetableSlot]
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class TuitionChatRequest(BaseModel):
    student_id: str
    session_id: str
    message: str

class TuitionSessionStateUpdate(BaseModel):
    session_id: str
    new_state: str  # RECAP, TEACH, GUIDED_PRACTICE, INDEPENDENT_PRACTICE, SUMMARY
